name: we_works_movie_app
description: WeWorks movie application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_simple_dependency_injection: ^2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  lint: ^2.0.20

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Strings
  nullsafety:

